# Template

# [[cms]]
# name = ""
# description = ""
# url = ""
# github_repo = ""
# awesome_repo = ""
# language = ""

# ---
# PHP
# ---

[[cms]]
name = "WordPress"
description = "WordPress is a free and open-source content management system (CMS) based on PHP and MySQL."
url = "https://wordpress.org"
github_repo = "WordPress/WordPress"
awesome_repo = "miziomon/awesome-wordpress"
language = "php"

[[cms]]
name = "Drupal"
description = "Drupal is a free and open-source content-management framework written in PHP and distributed under the GNU General Public License."
url = "https://www.drupal.org"
github_repo = "drupal/drupal"
awesome_repo = "mrsinguyen/awesome-drupal"
language = "php"

[[cms]]
name = "Joomla!"
description = "Joomla is a free and open-source content management system (CMS) for publishing web content. It is built on a model–view–controller web application framework that can be used independently of the CMS."
url = "https://www.joomla.org"
github_repo = "joomla/joomla-cms"
language = "php"

[[cms]]
name = "Croogo"
description = "A CakePHP powered Content Management System."
url = "http://www.croogo.org"
github_repo = "croogo/croogo"
language = "php"

[[cms]]
name = "FUEL CMS"
description = "A CodeIgniter Content Management System."
url = "http://www.getfuelcms.com"
github_repo = "daylightstudio/FUEL-CMS"
language = "php"

[[cms]]
name = "Grav"
description = "Modern, Crazy Fast, Ridiculously Easy and Amazingly Powerful Flat-File CMS."
url = "http://getgrav.org"
github_repo = "getgrav/grav"
language = "php"

[[cms]]
name = "Pagekit"
description = "Pagekit is a modular and lightweight CMS built with Symfony components and Vue.js."
url = "https://pagekit.com"
github_repo = "pagekit/pagekit"
language = "php"

[[cms]]
name = "Bolt"
description = "Bolt is a simple CMS written in PHP. It is based on Silex and Symfony components, uses Twig and either SQLite, MySQL or PostgreSQL."
url = "https://github.com/bolt/bolt"
github_repo = "bolt/bolt"
language = "php"

[[cms]]
name = "Anchor CMS"
description = "A lightweight blog CMS for PHP."
url = "http://anchorcms.com/"
github_repo = "anchorcms/anchor-cms"
language = "php"

[[cms]]
name = "Pico"
description = "Pico is a stupidly simple, blazing fast, flat file CMS."
url = "http://picocms.org/"
github_repo = "picocms/Pico"
language = "php"

[[cms]]
name = "Cockpit CMS"
description = "Add content management functionality to any site."
url = "http://getcockpit.com"
github_repo = "COCOPi/cockpit"
language = "php"

[[cms]]
name = "Bootstrap CMS"
description = "A PHP CMS powered by Laravel 5 and Sentry"
github_repo = "BootstrapCMS/CMS"
language = "php"

[[cms]]
name = "Borgert CMS"
description = "A simple CMS to start projects in Laravel 5.3 containing some modules. Blog, Pages, Products, Mailbox, Image Gallery and Users."
github_repo = "odirleiborgert/borgert-cms"
language = "php"

[[cms]]
name = "Fork CMS"
description = "Fork is an open source CMS using Symfony Components."
url = "http://www.fork-cms.com"
github_repo = "forkcms/forkcms"
language = "php"

[[cms]]
name = "Pimcore Platform"
description = "Content & Product Management Framework (CMS/PIM/E-Commerce)."
url = "http://www.pimcore.org/"
github_repo = "pimcore/pimcore"
language = "php"

[[cms]]
name = "SilverStripe"
description = "SilverStripe is the intuitive content management system and flexible framework loved by editors and developers alike. Equip your web teams to achieve outstanding results."
url = "http://silverstripe.org/"
github_repo = "silverstripe/silverstripe-framework"
language = "php"

[[cms]]
name = "Lavalite"
description = "CMS Built with Laravel 5.2 and Bootstrap 3."
url = "http://www.lavalite.org"
github_repo = "LavaLite/cms"
language = "php"

[[cms]]
name = "Contao"
description = "Contao is a web-based Open Source CMS, which generates accessible websites. It supports multiple languages and can easily be learned and extended."
url = "https://contao.org/en/"
github_repo = "contao/core"
language = "php"

[[cms]]
name = "Microweber"
description = "Microweber is a new generation content management system that allows you to create a website using drag and drop. You can easily manipulate the content and the layout of your pages. No coding skills are required."
url = "https://microweber.com"
github_repo = "microweber/microweber"
language = "php"

[[cms]]
name = "PyroCMS"
description = "PyroCMS is an MVC PHP Content Management System built to be easy to use, theme and develop with. It is used by individuals and organizations of all sizes around the world."
url = "https://www.pyrocms.com/"
github_repo = "pyrocms/pyrocms"
awesome_repo = "websemantics/awesome-pyrocms"
language = "php"

[[cms]]
name = "Textpattern CMS"
description = "A flexible, elegant and easy-to-use content management system. Textpattern is both free and open source."
url = "http://textpattern.com/"
github_repo = "textpattern/textpattern"
awesome_repo = "drmonkeyninja/awesome-textpattern"
language = "php"

# -------------
# Closed Source
# -------------

[[cms]]
name = "SquareSpace"
description = "Squarespace is a SaaS-based content management system-integrated website builder, blogging platform and hosting service."
url = "https://www.squarespace.com"

[[cms]]
name = "Siteleaf"
description = "Supports Jekyll, user collaboration, publishing to AWS S3, GitHub Pages, FTP, and more."
url = "http://www.siteleaf.com"

[[cms]]
name = "ExpressionEngine"
description = "general purpose content management system written in object-oriented PHP and using MySQL for data storage."
url = "https://ellislab.com/expressionengine"

[[cms]]
name = "Craft CMS"
description = "Craft CMS is a focused content management system for developers, designers, and web professionals that blends flexibility, power, and ease of use for clients."
url = "https://craftcms.com"

[[cms]]
name = "prismic.io"
description = "A hosted, API based and developer friendly CMS backend. We take care of upgrades, scalability and security."
url = "https://prismic.io"

[[cms]]
name = "Built.io Contentstack"
description = "Headless CMS divides front-end from backend architecture to send content to multiple devices and platforms without creating content differently each time."
url = "https://www.built.io/products/contentstack/overview"

[[cms]]
name = "Osmek"
description = "Osmek is a new kind of CMS, built in the cloud so your content is available where and how you need it. It's a beautiful interface for creating content, and a powerful set of APIs for retrieving it."
url = "http://osmek.com"

[[cms]]
name = "Cloud CMS"
description = "Shatter the limits imposed by your old, legacy CMS. Our headless, API-first Content Management System provides everything needed for scalable, multi-device publishing through SaaS and On-Premise delivery"
url = "https://www.cloudcms.com"

[[cms]]
name = "Contentful"
description = "Contentful is an API-first CMS focused on the simplicity of development. Manage structured content in websites and apps."
url = "https://www.contentful.com"

[[cms]]
name = "Cosmic JS"
description = "Cosmic JS is a cloud-hosted content platform that offers a flexible and intuitive CMS API.  Build websites and applications with more freedom and manage content easier."
url = "https://cosmicjs.com"

[[cms]]
name = "Prose"
description = "Prose is a content editor for GitHub designed for managing websites."
url = "http://prose.io"

[[cms]]
name = "Weebly"
description = "Weebly makes it surprisingly easy to create a high-quality website, blog or online store. Over 30 million people use Weebly to bring their unique ideas to life."
url = "https://www.weebly.com"

[[cms]]
name = "Wix"
description = "Create a free website with Wix.com. Customize with Wix' free website builder, no coding skills needed. Choose a design, begin customizing and be online today!"
url = "http://www.wix.com"

[[cms]]
name = "Blogger"
description = "Publish your passions your way. Whether you’d like to share your knowledge, experiences or the latest news, create a unique and beautiful blog for free."
url = "https://www.blogger.com"

[[cms]]
name = "Medium"
description = "Welcome to Medium, a place to read, write, and interact with the stories that matter most to you. Every day thousands of new voices share…"
url = "http://medium.com"

[[cms]]
name = "Jimdo"
description = "Create a professional website, online store or blog in minutes with Jimdo's website builder. Choose one of our responsive templates, and get started!"
url = "http://www.jimdo.com"

# ----------
# JavaScript
# ----------

[[cms]]
name = "Netlify CMS"
description = "A CMS for Static Site Generators."
github_repo = "netlify/netlify-cms"
language = "javascript"

[[cms]]
name = "KeystoneJS"
description = "The open source framework for developing database-driven websites, applications and APIs in Node.js. Built on Express and MongoDB."
url = "http://keystonejs.com"
github_repo = "keystonejs/keystone"
language = "javascript"

[[cms]]
name = "Relax"
description = "New generation CMS on top of React, Redux and GraphQL."
github_repo = "relax/relax"
language = "javascript"

[[cms]]
name = "Ghost"
description = "Ghost is an open source publishing platform which is beautifully designed, easy to use, and free for everyone."
url = "https://ghost.org"
github_repo = "tryghost/Ghost"
language = "javascript"

[[cms]]
name = "We.js Framework"
description = "Extensible Node.js MVC framework."
url = "http://wejs.org/"
github_repo = "wejs/we"
language = "javascript"

[[cms]]
name = "PencilBlue"
description = "Business class content management for Node.js (plugins, server cluster management, data-driven pages)."
url = "https://pencilblue.org"
github_repo = "pencilblue/pencilblue"
language = "javascript"

[[cms]]
name = "Cody"
description = "Javascript Content Management System running on Node.js."
url = "http://howest.cody-cms.org"
github_repo = "jcoppieters/cody"
language = "javascript"

[[cms]]
name = "Apostrophe"
description = "Apostrophe is a content management system. This core module provides rich content editing as well as essential services to tie Apostrophe to your Express application."
github_repo = "punkave/apostrophe"
language = "javascript"

[[cms]]
name = "Reaction"
description = "Reaction is a modern reactive, real-time event driven ecommerce platform."
url = "https://reactioncommerce.com/"
github_repo = "reactioncommerce/reaction"
language = "javascript"

[[cms]]
name = "Directus"
description = "Directus is a headless CMS written in backbone.js that provides a feature-rich environment for rapid development and management of custom database schemas."
url = "http://getdirectus.com"
github_repo = "directus/directus"
language = "javascript"

[[cms]]
name = "Webhook"
description = "Webhook lets you build a custom CMS with matching HTML templates in about a minute. Webhook is built with Node JS, Grunt, Firebase and Swig."
url = "http://www.webhook.com"
github_repo = "webhook/webhook"
language = "javascript"

[[cms]]
name = "CMS.js"
description = "CMS.js is fully client-side, Javascript site generator in the spirit of Jekyll that uses plain ol' HTML, CSS and Javascript to generate your website. CMS.js is like a file-based CMS. It takes your content, renders Markdown and delivers a complete website in Single-Page App fashion...without the aid of server-side scripting."
url = "http://cdmedia.github.io/cms.js"
github_repo = "cdmedia/cms.js"
language = "javascript"

[[cms]]
name = "Respond CMS"
description = "Angular 2 + Lumen PHP + Static HTML sites.  Respond 6 is a responsive CMS that features Bootstrap 3, a complete REST API,  templates, plugins, and more."
url = "https://respondcms.com"
github_repo = "madoublet/respond"
language = "javascript"

[[cms]]
name = "Jekyll Admin"
description = "A Jekyll plugin that provides users with a traditional CMS-style graphical interface to author content and administer Jekyll sites."
url = "https://jekyll.github.io/jekyll-admin/"
github_repo = "jekyll/jekyll-admin"
language = "javascript"

# ----
# Ruby
# ----

[[cms]]
name = "Alchemy CMS"
description = "Alchemy is a powerful, flexible and user centric Rails CMS."
url = "http://alchemy-cms.com"
github_repo = "AlchemyCMS/alchemy_cms"
language = "ruby"

[[cms]]
name = "Camaleon CMS"
description = "Camaleon CMS is a dynamic and advanced content management system based on Ruby on Rails 4."
url = "http://camaleon.tuzitio.com/"
github_repo = "owen2345/camaleon-cms"
language = "ruby"

[[cms]]
name = "ComfortableMexicanSofa "
description = "ComfortableMexicanSofa is a powerful Rails 4 CMS Engine."
github_repo = "comfy/comfortable-mexican-sofa"
language = "ruby"

[[cms]]
name = "LocomotiveCMS"
description = "A platform to create, publish and edit sites."
url = "http://locomotive.works"
github_repo = "locomotivecms/engine"
language = "ruby"

[[cms]]
name = "Publify"
description = "A self hosted Web publishing platform on Rails."
url = "http://publify.co"
github_repo = "publify/publify"
language = "ruby"

[[cms]]
name = "Radiant CMS"
description = "Radiant is a no-fluff, open source content management system designed for small teams."
url = "http://radiantcms.org/"
github_repo = "radiant/radiant"
language = "ruby"

[[cms]]
name = "Refinery CMS"
description = "An extendable Ruby on Rails CMS that supports Rails 4.2+."
url = "http://refinerycms.com"
github_repo = "refinery/refinerycms"
awesome_repo = "refinerycms-contrib/awesome-refinerycms"
language = "ruby"

[[cms]]
name = "Spina"
description = "GitHub - denkGroot/Spina: Spina CMS."
url = "http://www.spinacms.com"
github_repo = "denkGroot/Spina"
language = "ruby"

[[cms]]
name = "Storytime"
description = "Storytime is a Rails 4+ CMS and blogging engine, with a core focus on content. It is built and maintained by @cultivatelabs."
github_repo = "CultivateLabs/storytime"
language = "ruby"

[[cms]]
name = "Nesta"
description = "A lightweight CMS, implemented in Sinatra."
url = "http://nestacms.com"
github_repo = "gma/nesta"
language = "ruby"

## ------
## Python
## ------

[[cms]]
name = "django CMS"
description = "The easy-to-use and developer-friendly CMS."
url = "http://www.django-cms.org"
github_repo = "divio/django-cms"
awesome_repo = "mishbahr/awesome-django-cms"
language = "python"

[[cms]]
name = "feinCMS"
description = "A Django-based CMS with a focus on extensibility and concise code."
url = "http://www.feincms.org/"
github_repo = "feincms/feincms"
language = "python"

[[cms]]
name = "Kotti"
description = "Kotti is a high-level, Pythonic web application framework based on Pyramid and SQLAlchemy. It includes an extensible Content Management System called the Kotti CMS."
url = "http://kotti.pylonsproject.org"
github_repo = "Kotti/Kotti"
language = "python"

[[cms]]
name = "Mezzanine"
description = "CMS framework for Django."
url = "http://mezzanine.jupo.org"
github_repo = "stephenmcd/mezzanine"
language = "python"

[[cms]]
name = "Opps Project"
description = "A Django-based CMS for the magazines, newspappers websites and portals with high-traffic."
url = "http://opps.github.io/opps/"
github_repo = "opps/opps"
language = "python"

[[cms]]
name = "Plone CMS"
description = "Plone is a user friendly Content Management System running on top of Python, Zope and the CMF."
url = "http://plone.org"
github_repo = "plone/Plone"
language = "python"

[[cms]]
name = "Quokka CMS"
description = "Quokka is a flexible content management platform powered by Python, Flask and MongoDB."
url = "http://www.quokkaproject.org"
github_repo = "quokkaproject/quokka"
language = "python"

[[cms]]
name = "Wagtail CMS"
description = "Wagtail is a content management system built on Django. It's focused on user experience, and offers precise control for designers and developers."
url = "http://wagtail.io"
github_repo = "torchbox/wagtail"
awesome_repo = "springload/awesome-wagtail"
language = "python"

[[cms]]
name = "Lektor"
description = "The lektor static file content management system"
url = "https://www.getlektor.com/"
github_repo = "lektor/lektor"
language = "python"

# ----
# .NET
# ----

[[cms]]
name = "Umbraco"
description = "The simple, flexible and friendly ASP.NET CMS used by more than 360,000 websites."
url = "http://umbraco.com"
github_repo = "umbraco/Umbraco-CMS"
awesome_repo = "leekelleher/awesome-umbraco"
language = "c#"

[[cms]]
name = "Orchard"
description = "Orchard is a free, open source, community-focused Content Management System built on the ASP.NET MVC platform."
url = "http://orchardproject.net"
github_repo = "OrchardCMS/Orchard"
language = "c#"

[[cms]]
name = "DotNetNuke (DNN)"
description = "DNN Platform is our free, open source web CMS and the foundation of every professional DNN solution. Over 750,000 organizations worldwide have built websites powered by the DNN Platform."
url = "http://www.dnnsoftware.com"
github_repo = "dnnsoftware/Dnn.Platform"
language = "c#"

[[cms]]
name = "Piranha CMS"
description = "Piranha is the fun, fast and lightweight .NET framework for developing cms-based web applications with an extra bite. It's built on ASP.NET MVC and Web Pages and is fully compatible with both Visual Studio and WebMatrix."
url = "http://piranhacms.org"
github_repo = "PiranhaCMS/Piranha"
language = "c#"

[[cms]]
name = "Composite C1"
description = "A web CMS that focus on UX and adaptability."
github_repo = "Orckestra/C1-CMS"
language = "c#"
